---
- name: 'Configurar Múltiples Interfaces, Guardar y Reiniciar Red'
  hosts: all
  gather_facts: false

  tasks:
    - name: '1. Aplicar configuración a cada interfaz especificada'
      # Este bucle iterará sobre la lista 'changes' que le pasamos desde la app.
      # Cada item tiene 'device', 'iface_name', 'ip' y 'mask'.
      loop: "{{ changes | default([]) }}"
      loop_control:
        loop_var: iface_config
      # Usamos 'when' para asegurar que la tarea solo se ejecute en el host correcto
      # para el que está destinada esta configuración de interfaz.
      when: iface_config.device == inventory_hostname
      ansible.builtin.raw: |
        #!/bin/sh
        # ============================================================================
        # == SCRIPT MODIFICADO PARA SOPORTAR OPERACIONES EN LOTE                    ==
        # ============================================================================
        
        # Si la interfaz empieza con 'br-', derivamos el nombre de la seccion UCI.
        # Ejemplo: 'br-lan' -> 'lan'
        if echo "{{ iface_config.iface_name }}" | grep -q '^br-'; then
          TARGET_SECTION=$(echo "{{ iface_config.iface_name }}" | sed 's/^br-//')
        else
          # Para otras interfaces, asumimos que el nombre de la interfaz es la seccion.
          TARGET_SECTION="{{ iface_config.iface_name }}"
        fi

        # Verificamos que la sección derivada realmente existe en la configuración.
        if ! uci show "network.$TARGET_SECTION" >/dev/null 2>&1; then
          echo "ERROR: La seccion UCI derivada '$TARGET_SECTION' no existe para la interfaz '{{ iface_config.iface_name }}' en {{ inventory_hostname }}." >&2
          exit 1
        fi
        
        # Aplicamos toda la configuración a la sección correcta
        uci set "network.$TARGET_SECTION.proto=static"
        uci set "network.$TARGET_SECTION.ipaddr={{ iface_config.ip }}"
        uci set "network.$TARGET_SECTION.netmask={{ iface_config.mask }}"
        
        # Guardamos los cambios en la memoria flash
        uci commit network
        
        echo "OK: Configuracion para {{ iface_config.iface_name }} aplicada y guardada en la seccion '$TARGET_SECTION'."
        exit 0
      register: config_result
      changed_when: "'OK:' in config_result.stdout"
      failed_when: config_result.rc != 0

    - name: '2. Reiniciar el servicio de red para aplicar TODOS los cambios'
      # Esta tarea se ejecuta una sola vez al final, después de que el bucle termine.
      ansible.builtin.raw: /etc/init.d/network restart
      ignore_errors: true
