---
- name: Consultar nombre de la red WiFi (SSID) en OpenWrt
  hosts: all
  gather_facts: false

  tasks:
    - name: Obtener el SSID de la primera interfaz WiFi con UCI (usando RAW)
      ansible.builtin.raw: uci get wireless.@wifi-iface[0].ssid
      register: uci_ssid_output
      changed_when: false

    - name: Mostrar el SSID encontrado
      ansible.builtin.debug:
        msg: "El SSID de la red WiFi es: {{ uci_ssid_output.stdout }}"
