---
- name: Mostrar las Reglas Actuales del Firewall
  hosts: all
  gather_facts: false

  tasks:
    - name: Ejecutar 'fw3 print' para listar las reglas activas
      ansible.builtin.raw: fw3 print
      register: firewall_rules
      changed_when: false

    - name: Mostrar las reglas del firewall
      ansible.builtin.debug:
        msg: |
          Reglas del Firewall Activas:
          {{ firewall_rules.stdout }}
