---
- name: Ver Actualizaciones de Paquetes Disponibles
  hosts: all
  gather_facts: false

  tasks:
    - name: Paso 1 - Actualizar la lista de paquetes (opkg update)
      ansible.builtin.raw: opkg update
      register: update_result
      changed_when: false

    - name: Mostrar resultado de 'opkg update'
      ansible.builtin.debug:
        msg: "{{ update_result.stdout_lines }}"

    - name: Paso 2 - Listar los paquetes que se pueden actualizar (sin instalar)
      ansible.builtin.raw: opkg list-upgradable
      register: upgradable_list
      changed_when: false

    - name: Mostrar la lista de paquetes actualizables
      ansible.builtin.debug:
        msg:
          - "================================================================"
          - " Paquetes con actualizaciones disponibles: "
          - "================================================================"
          - "{{ upgradable_list.stdout_lines | join('\\n') }}"
          - ""
          - "Para instalar estas actualizaciones, ejecuta el playbook 'Realizar Actualizacion Sistema'."
