---
- name: Obtener Informacion General del Sistema
  hosts: all
  gather_facts: false

  tasks:
    - name: Leer la version de OpenWrt
      ansible.builtin.raw: cat /etc/openwrt_release | grep 'DISTRIB_DESCRIPTION'
      register: version_info
      changed_when: false

    - name: Comprobar el tiempo de actividad (uptime)
      ansible.builtin.raw: uptime
      register: uptime_info
      changed_when: false

    - name: Comprobar el uso de memoria RAM
      ansible.builtin.raw: free -h
      register: memory_info
      changed_when: false

    - name: Mostrar Informacion Recopilada
      ansible.builtin.debug:
        msg: |
          Version: {{ version_info.stdout }}
          Uptime: {{ uptime_info.stdout | trim }}
          Uso de Memoria:
          {{ memory_info.stdout }}
