---
- name: Forzar Sincronizacion de Hora con NTP
  hosts: all
  gather_facts: false

  tasks:
    - name: Mostrar la hora actual antes de sincronizar
      ansible.builtin.raw: date
      register: date_before
      changed_when: false

    - name: Ejecutar el cliente NTP para forzar la sincronizacion
      ansible.builtin.raw: /etc/init.d/sysntpd restart
      register: ntp_sync
      changed_when: false

    - name: Esperar 5 segundos para que la sincronizacion se complete
      ansible.builtin.pause:
        seconds: 5

    - name: Mostrar la hora despues de sincronizar
      ansible.builtin.raw: date
      register: date_after
      changed_when: false
      
    - name: Mostrar Resultados
      ansible.builtin.debug:
        msg: |
          Hora antes: {{ date_before.stdout | trim }}
          Resultado del comando de sincronizacion: {{ ntp_sync.stdout | trim }}
          Hora despues: {{ date_after.stdout | trim }}
