---
- name: Get Disk Usage
  hosts: all
  gather_facts: false
  vars:
    ansible_python_interpreter: /bin/true
  tasks:
    - name: Get Disk Usage
      ansible.builtin.raw: |
        echo "$(df -h / | tail -n 1 | awk '{print $4 " libres de " $2 " (" $5 " usados)"}' 2>/dev/null || echo "N/A")"
      register: result
      changed_when: false