---
- name: Get Firmware
  hosts: all
  gather_facts: false
  vars:
    ansible_python_interpreter: /bin/true
  tasks:
    - name: Get Firmware
      ansible.builtin.raw: |
        grep OPENWRT_RELEASE /etc/os-release | awk -F'"' '{print $2}' 2>/dev/null || echo "N/A"
      register: result
      changed_when: false
