---
- name: Get IP Address
  hosts: all
  gather_facts: false
  vars:
    ansible_python_interpreter: /bin/true
  tasks:
    - name: Get IP
      ansible.builtin.raw: |
        echo "$(ip route get 8.8.8.8 | awk -F"src " 'NR==1{split($2,a," ");print a[1]}' 2>/dev/null || echo "N/A")"
      register: result
      changed_when: false