---
- name: Get WiFi Clients
  hosts: all
  gather_facts: false
  vars:
    ansible_python_interpreter: /bin/true
  tasks:
    - name: Get WiFi Clients
      ansible.builtin.raw: |
        echo "$( (iw dev $(iw dev | grep "Interface" | cut -d " " -f 2) station dump | grep Station | awk '{print $2}' | tr '\n' ', ') 2>/dev/null || echo "Ninguno")"
      register: result
      changed_when: false