---
- name: Cambiar la contrasena del usuario root
  hosts: all
  gather_facts: false

  tasks:
    - name: Cambiar la contrasena de root de forma no interactiva
      ansible.builtin.raw: echo -e "{{ new_root_password }}\n{{ new_root_password }}" | passwd
      
    - name: Mensaje de confirmacion
      ansible.builtin.debug:
        msg: "Se ha intentado cambiar la contraseña en {{ inventory_hostname }}. Por favor, actualiza tu fichero 'hosts' de Ansible."
