---
- name: Configurar IPv4 en la interfaz LAN
  hosts: all
  gather_facts: false

  tasks:
    - name: Aplicar nueva direccion IP (si se proporciono)
      ansible.builtin.raw: uci set network.lan.ipaddr='{{ new_ip }}'
      when: new_ip is defined and new_ip != ""

    - name: Aplicar nueva mascara de red (si se proporciono)
      ansible.builtin.raw: uci set network.lan.netmask='{{ new_mask }}'
      when: new_mask is defined and new_mask != ""
      
    - name: Aplicar nuevo gateway (si se proporciono)
      ansible.builtin.raw: uci set network.lan.gateway='{{ new_gateway }}'
      when: new_gateway is defined and new_gateway != ""

    - name: Guardar cambios de red
      ansible.builtin.raw: uci commit network

    - name: Reiniciar servicio de red para aplicar cambios
      ansible.builtin.raw: /etc/init.d/network restart
