--- Ansible-OpenWrt-UI-main/playbook_library/action_get_wifi_password.yml (nuevo archivo) ---
---
- name: Obtener detalles de configuracion WiFi para una radio
  hosts: all
  gather_facts: false

  tasks:
    - name: Obtener la clave de la interfaz WiFi especificada
      ansible.builtin.raw: uci get wireless.@wifi-iface[{{ radio_index }}].key
      register: uci_key_output
      changed_when: false
      failed_when: false # No queremos que falle si la clave no existe (red abierta)

    - name: Obtener el cifrado de la interfaz
      ansible.builtin.raw: uci get wireless.@wifi-iface[{{ radio_index }}].encryption
      register: uci_encryption_output
      changed_when: false
      failed_when: false

    - name: Devolver los valores en un formato parseable
      ansible.builtin.debug:
        msg: |
          KEY::{{ uci_key_output.stdout | trim }}
          ENCRYPTION::{{ uci_encryption_output.stdout | trim }}
