---
- name: Cambiar la contraseña de root
  hosts: all
  gather_facts: false

  tasks:
    - name: Establecer la nueva contraseña para el usuario root
      ## SECURITY: La variable se encierra entre comillas simples (') dentro del comando 'echo'
      ## para añadir una capa de defensa contra la inyección de comandos. La validación
      ## principal y más importante sigue estando en el backend (app.py).
      ansible.builtin.raw: "echo '{{ new_root_password }}' | passwd --stdin root"
      register: password_change
      changed_when: password_change.rc == 0

    - name: Mostrar resultado
      ansible.builtin.debug:
        msg: "Comando de cambio de contraseña ejecutado. Salida: {{ password_change.stdout | default('N/A') }} | Error: {{ password_change.stderr | default('N/A') }}"
